# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
ci:
  skip: [pylint]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        files: lib/

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        files: lib/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
    -   id: ruff

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint "lib/"
        language: system
        types: [ python ]
        pass_filenames: false
        args:
            [
                "-rn", # Only display messages
                "-sn", # Don't display the score
            ]
